"""Ish kuni: check-in (GPS + selfie), baholar, ishonchlilik hodisalari (TZ 10, 13, 15)

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-28 14:58:33.916685
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkins",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("assignment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("accuracy_m", sa.Float(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=False),
        sa.Column("selfie_key", sa.String(length=200), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
            name=op.f("fk_checkins_assignment_id_assignments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkins")),
    )
    op.create_index(op.f("ix_checkins_assignment_id"), "checkins", ["assignment_id"], unique=False)
    op.create_table(
        "reliability_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("delta", sa.SmallInteger(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("assignment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_reliability_events_assignment_id_assignments")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reliability_events_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reliability_events")),
    )
    op.create_index(op.f("ix_reliability_events_user_id"), "reliability_events", ["user_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("assignment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("author_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_role", sa.String(length=10), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("comment", sa.String(length=300), nullable=True),
        sa.Column("is_auto", sa.Boolean(), nullable=False),
        sa.Column("hidden_by_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("visible_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_reviews_assignment_id_assignments"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_reviews_author_id_users")),
        sa.ForeignKeyConstraint(["target_id"], ["users.id"], name=op.f("fk_reviews_target_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("assignment_id", "author_id", name=op.f("uq_reviews_assignment_id")),
    )
    op.create_index(op.f("ix_reviews_assignment_id"), "reviews", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_reviews_target_id"), "reviews", ["target_id"], unique=False)
    op.create_index(op.f("ix_reviews_visible_at"), "reviews", ["visible_at"], unique=False)
    op.add_column("assignments", sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assignments", sa.Column("arrival_confirmed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assignments", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assignments", sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assignments", sa.Column("auto_confirmed", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("assignments", sa.Column("cash_received", sa.BigInteger(), nullable=True))
    op.add_column("assignments", sa.Column("no_show_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("assignments", sa.Column("problem", sa.String(length=300), nullable=True))
    op.add_column("assignments", sa.Column("timeline", sa.JSON(), nullable=False, server_default="{}"))
    op.add_column(
        "employer_profiles", sa.Column("reliability", sa.SmallInteger(), nullable=False, server_default="100")
    )
    op.add_column("worker_profiles", sa.Column("suspended_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_profiles", "suspended_until")
    op.drop_column("employer_profiles", "reliability")
    op.drop_column("assignments", "timeline")
    op.drop_column("assignments", "problem")
    op.drop_column("assignments", "no_show_at")
    op.drop_column("assignments", "cash_received")
    op.drop_column("assignments", "auto_confirmed")
    op.drop_column("assignments", "confirmed_at")
    op.drop_column("assignments", "finished_at")
    op.drop_column("assignments", "arrival_confirmed_at")
    op.drop_column("assignments", "arrived_at")
    op.drop_index(op.f("ix_reviews_visible_at"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_target_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_assignment_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_reliability_events_user_id"), table_name="reliability_events")
    op.drop_table("reliability_events")
    op.drop_index(op.f("ix_checkins_assignment_id"), table_name="checkins")
    op.drop_table("checkins")
    # ### end Alembic commands ###
