"""Sevimli va bloklangan ishchilar, T−60 qisman to'lgan buyurtma tanlovi (TZ 5, 6, 7)

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-28 15:18:20.312058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employer_blocks",
        sa.Column("employer_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("worker_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["users.id"], name=op.f("fk_employer_blocks_employer_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["users.id"], name=op.f("fk_employer_blocks_worker_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("employer_id", "worker_id", name=op.f("pk_employer_blocks")),
    )
    op.create_index(op.f("ix_employer_blocks_worker_id"), "employer_blocks", ["worker_id"], unique=False)
    op.create_table(
        "employer_favorites",
        sa.Column("employer_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("worker_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["users.id"], name=op.f("fk_employer_favorites_employer_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["users.id"], name=op.f("fk_employer_favorites_worker_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("employer_id", "worker_id", name=op.f("pk_employer_favorites")),
    )
    op.add_column("orders", sa.Column("favorites_sent_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("orders", sa.Column("partial_asked_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("orders", sa.Column("partial_decision", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "partial_decision")
    op.drop_column("orders", "partial_asked_at")
    op.drop_column("orders", "favorites_sent_at")
    op.drop_table("employer_favorites")
    op.drop_index(op.f("ix_employer_blocks_worker_id"), table_name="employer_blocks")
    op.drop_table("employer_blocks")
    # ### end Alembic commands ###
